// Generated by CoffeeScript 1.7.1
(function() {
  var extends_module,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  extends_module = angular.module('classy-extends', ['classy-core']);

  extends_module.classy.plugin.controller({
    name: 'extends',
    classObjs: {},
    waitingClassConstructors: {},
    options: {
      enabled: true,
      "super": '_super'
    },
    fnTest: (function() {
      var fn;
      fn = void 0;
      return function() {
        if (fn == null) {
          fn = /xyz/.test('function(){xyz;}') ? RegExp("\\b" + this.options["super"] + "\\b") : /.*/;
        }
        return fn;
      };
    })(),
    convertInject: function(classObj) {
      var i, _i, _inject, _len, _ref;
      if (angular.isArray(classObj.inject)) {
        _inject = {};
        _ref = classObj.inject;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          i = _ref[_i];
          _inject[i] = '.';
        }
        return classObj.inject = _inject;
      }
    },
    extend: function(classConstructor, classObj, baseClassObj) {
      var dep, isInitialized, key, prop, val, _i, _len, _ref, _ref1;
      for (prop in baseClassObj) {
        if (typeof classObj[prop] === 'undefined') {
          classObj[prop] = classConstructor.prototype[prop] = baseClassObj[prop];
        } else if (angular.isFunction(classObj[prop]) && this.fnTest().test(classObj[prop]) && prop !== 'constructor') {
          classObj[prop] = classConstructor.prototype[prop] = (function(name, fn, parentName) {
            return function() {
              var ret, self, tmp;
              tmp = this[parentName];
              self = this;
              this[parentName] = function(args) {
                return baseClassObj[name].apply(self, args || []);
              };
              ret = fn.apply(this, arguments);
              this[parentName] = tmp;
              return ret;
            };
          })(prop, classObj[prop], this.options["super"]);
        }
      }
      this.convertInject(classObj);
      this.convertInject(baseClassObj);
      isInitialized = classConstructor.__classDepNames != null;
      if (isInitialized && (classConstructor.__classyControllerInjectObject == null)) {
        classConstructor.__classyControllerInjectObject = {};
        _ref = classConstructor.__classDepNames;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          dep = _ref[_i];
          classConstructor.__classyControllerInjectObject[dep] = '.';
        }
      }
      _ref1 = baseClassObj.inject;
      for (key in _ref1) {
        val = _ref1[key];
        classObj.inject[key] = val;
        if (isInitialized) {
          if (__indexOf.call(classConstructor.$inject, key) < 0) {
            classConstructor.$inject.push(key);
            classConstructor.__classDepNames.push(key);
          }
          classConstructor.__classyControllerInjectObject[key] = val;
        }
      }
    },
    preInitBefore: function(classConstructor, classObj, module) {
      var baseClassObj, className, waitingClassConstructor, waitingClassObj, _ref;
      if (classObj["extends"]) {
        baseClassObj = this.classObjs[classObj["extends"]];
        if (baseClassObj) {
          this.extend(classConstructor, classObj, baseClassObj);
        } else {
          this.waitingClassConstructors[classObj.name] = classConstructor;
        }
      }
      this.classObjs[classObj.name] = classObj;
      _ref = this.waitingClassConstructors;
      for (className in _ref) {
        waitingClassConstructor = _ref[className];
        waitingClassObj = this.classObjs[className];
        if (waitingClassObj["extends"] === classObj.name) {
          this.extend(waitingClassConstructor, waitingClassObj, classObj);
        }
      }
    }
  });

}).call(this);
